# Generated by Django 4.2.19 on 2025-02-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="values",
            new_name="game_map",
        ),
    ]
